version: 1
formatters:
  simple:
    format: '[%(name)s, %(module)s, %(levelname)s]: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: log.log
loggers:
  dev:
    handlers: [console]
root:
  handlers: []